### ISSUE TITLE
H264 and HEVC are the only supported codecs (NOT flatpak version)

### ISSUE THREAD

**Issue by Admiral-Jezza** [dec05eba/gpu-screen-recorder-issues#59]
**Describe the bug**
H264, H264 Software, HEVC, and HEVC 10 bit are the only supported codecs. AV1, VP8 and VP9 are listed as "not available" despite using the regular clone and not the flatpak version.

**To Reproduce**
Open the GTK version and select the "Video codec" drop down menu. On the CLI I used `gpu-screen-recorder -w screen -f 60 -a default_output -k av1 -o "$HOME/[NAME]/Videos/video.mp4"` and it returned `Warning: selected video codec av1 is not supported, trying h264 instead`.

**Screenshots**
Not needed.

**Desktop (please complete the following information):**
 - X11 or Wayland: X11
- Desktop environment/Window Manager: KDE Plasma 5.27.11
 - Distro: Mint 22
 - GPU: RTX 2060
 - Version (latest flatpak version, aur or source): Source 4.2.4 2024-10-27

**Additional context**
Here's my drm_info log: [log.txt](https://github.com/user-attachments/files/17536082/log.txt)

Recording games, desktop etc, and audio work perfectly fine in the other available codecs. 

- [No] I played the video with the command `mpv --no-config video.mp4` (if applicable)
- [No] I use a laptop with an integrated GPU and a dedicated GPU

**Comment by dec05eba** [comment]
GPU Screen Recorder cant know the exact reason why a codec is not available so it gives a generic error for it, but in your case with RTX 2060 the reason is simple. Your gpu doesn't support AV1 encoding: https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new it's only available since RTX 4000 series. Nvidia also doesn't support VP8 and VP9.
