### ISSUE TITLE
[QUESTION] Using iGPU instead of GPU

### ISSUE THREAD

**Issue by bpc1** [dec05eba/gpu-screen-recorder-issues#6]
I have 6700XT, Ryzen 7600 combo and 7000s series come with iGPUs capable of recording I was wondering would it be possible to offload the encoding to the iGPU instead of the main GPU?

**Comment by dec05eba** [comment]
The gpu that is displaying graphics on your screen is used and it has to be that gpu (since its the gpu that has the graphics to record). If you want to record with igpu you have to change your system config to default to igpu and use the equivalent of prime-run for amd (or maybe it works with amd too, I dont know) to run the application itself with another gpu.
I dont know if I want to add the option to transfer graphics between gpus (since that has to go through system ram normally, which defeats the purpose of this software) unless there is a way to transfer gpu memory between two different gpus of different types (intel igpu to nvidia, nvidia to intel igpu or amd) directly in an efficient way.

**Comment by bpc1** [comment]
Thanks for the quick answer. Makes sense, especially since the overhead of the hw recording is already super minimal.
