### ISSUE TITLE
Running as Cron Job

### ISSUE THREAD

**Issue by Cyber5imon** [dec05eba/gpu-screen-recorder-issues#62]
I'm trying to record my entire screen 24/7 in 1 hour segments.
The best way I've found to do this is run the following command in a cron job every hour
```
timeout 3600 flatpak run --command=gpu-screen-recorder com.dec05eba.gpu_screen_recorder -w DP-3 -f 15 -k hevc -bm cbr -q 1024 -cr full -o "$file"
```
This stopped working once I moved to Wayland and now throws the following error
```
gsr error: gsr_egl_create_window failed: wl_display_connect failed
gsr error: failed to load opengl
```

Any ideas on how to run this in cron?

**Comment by dec05eba** [comment]
Sorry I dont know since I dont use cronjob. I assume the issue is that the cronjob is not running as the same user as you are running the wayland session on (your user), so it fails to connect to the wayland server (that is being run by your user).
Btw, this github page is only for reporting issues. If you have questions take a look at https://git.dec05eba.com/?p=about instead. But this question is more of a generic question about wayland usage in cronjob and not about gpu screen recorder itself.

**Comment by Cyber5imon** [comment]
Ok. Sorry for creating the issue in GitHub. I should have just emailed you. If you ever run across a use case where someone is trying to run gpu-screen-recorder in cron or under another user and find a solution, please let me know. Thank you!

**Comment by Nama** [comment]
For GUI tools to work without running them from the GUI, you need to set some variables.

On sway, it's those:
```
export WAYLAND_DISPLAY="wayland-1"
export SWAYSOCK=$(ls /run/user/1000/sway-ipc.1000.*.sock)
```
The first one might be enough, not sure tho.
Check your environment variables from a GUI terminal.
