### ISSUE TITLE
[BUG] Screen recording resolution calculation

### ISSUE THREAD

**Issue by porridgewithraisins** [dec05eba/gpu-screen-recorder-issues#65]
**Describe the bug**
Hi, you might recognise me from the emails where I implemented the beginnings of region capture for x11/intel.

### Context

I don't know if I am using the right terms here, so bear with me. I have a laptop, where I want to have fractional scaling. And you know the story of that on linux. The solution I use (and it works well) is setting xfce window manager zoom to 2x, and then scale the display to 1.6x. What this seems to do is render the desktop to a larger canvas, but the windows on that canvas are all 2x'd. So this ends up giving a good result. I have to set GDK_SCALE_whatever and QT_whatever also.

### Old behaviour

In this setup, gpu-screen-recorder used to give me proper results. For example, [this video](http://0x0.st/XD4-.mp4) from april 2023. I had the same desktop scaling setup back then as well (I think, because I don't remember changing anything). And it recorded fine, as you can see in the video, at 1920x1200 resolution (my screen resolution).

### New behaviour

Now, the videos I record look like [this](http://0x0.st/XD4o.mp4). What could be the reason? Now, it records at the 1.6x scaled 3072x1920 resolution.

**Command ran**
`gpu-screen-recorder -w screen -f 60 -o /tmp/lol.mp4`

**Desktop (please complete the following information):**
 - X11 or Wayland: X11
- Desktop environment/Window Manager: xfce, xfwm4 4.18.0-3
 - Distro: Arch
 - GPU: AMD Ryzen 5 3600 Integrated GPU
 - Version (latest flatpak version, aur or source): AUR, happens with source as well.

**Additional context**
[drm-info.txt](https://github.com/user-attachments/files/17682293/drm-info.txt).

**Comment by dec05eba** [comment]
Hmm thats weird. Can you run xrandr and post the output?

**Comment by dec05eba** [comment]
One part did change long ago. Its needed for proper handling on x11, for example with rotated monitors. I can see if i can maybe try and fix it. When you said scaling the display, did you mean using `xrandr --output DP-1 --scale 1.6` for example?

**Comment by porridgewithraisins** [comment]
I did it in the xfce display settings, but now I turned that back to 1x and did it with your xrandr command, and it seems to do the same thing. So yes.

**Comment by dec05eba** [comment]
Ah ok no I remembered wrong. I checked git history and it has to do with capturing external monitor on laptops with dedicated nvidia gpu on x11. The external monitor info wont be available in the drm info output (as seen when running the drm_info command) for the monitor connected to the nvidia gpu (the hdmi slot), as nvidia doesn't use linux drm api on x11.

Anyways, I pushed a fix for this issue. Can you update to the latest aur version and test again? Note that this only fixes this issue for monitor capture. If you try to capture a fullscreen window instead then it will capture at 3072x1920, although it wont have black bars on the side like in the video you posted. There isn't really anything to do about that, the window texture itself is that size.

**Comment by porridgewithraisins** [comment]
Yes, I ran a `git pull`, built it and all seems well.

Also, I don't use an external nvidia gpu, unless you mentioned that off-hand.

About the full screen window thing: You're right that it records at a higher resolution, but when I send it on e.g whatsapp, or open it in VLC, the black bars don't appear, so that's fine by me, I guess I down-scale the video after the fact, although that does require a re-encode as I understand it. Can you tell me how the bars disappeared BTW?

Also, do you think it makes sense to have the downscaling feature in this app itself? Or in general ffmpeg "output filters"? My favorite windows screen recorder ShareX had that feature.

**Comment by dec05eba** [comment]
The black bars when recording the monitor appeared because it said the monitor size was 3072x1920 but the framebuffer captured itself was 1920x1200 so it just displayed it in the center of the video (thats how gpu screen recorder behaves).
When capturing a window the window texture itself is that larger size so gpu screen recorder records that, so the video size matches the window texture size so there aren't any black bars.

The reason why the monitor framebuffer isn't larger than 1920x1200 but the window is is because when you scale the output in x11 x11 will scale every window, but when it finally displays it on the screen it will downscale it to the monitors real size and display that. gpu screen recorder captures that final framebuffer when you record the monitor.

>Also, do you think it makes sense to have the downscaling feature in this app itself?

Thats a feature that was added very recently :) . Use the -s option, for example -s 1920x1080. Before this option was only for focused window to set the size, but now it sets the video resolution and scales the captured content to that video resolution. (This option sets the max video resolution, the resolution in any axis can be different because it respects the aspect ratio of the captured content).

**Comment by porridgewithraisins** [comment]
Great, thanks for the quick resolution. Upgraded to latest gpu-screen-recorder, -gtk as well. Everything works fine.
